M48
; DRILL file {KiCad 9.0.9-9.0.9~ubuntu24.04.1} date 2026-06-22T01:19:56-0300
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-06-22T01:19:56-03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.9-9.0.9~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.100
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X266.99Y-124.74
X267.01Y-35.96
T2
X124.69Y-34.03
X124.71Y-124.16
M30
